### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by RadonCoding** [melotic/rekk#1] opened 2022-08-21 09:22 UTC
Hello. Your project doesn't seem to work with my [binary](https://drive.google.com/file/d/1azK9DwDVY_r0B-Ag3JVTNNtcMK_vqOsl/view?usp=sharing) could you look into it?

I can also send you the source code of the binary if you do not have a virtual machine.

**Comment by melotic** [comment] 2022-08-22 03:59
It looks like google removed the binary as it violated their ToS.

But I suspect the problem is because rekk disassembled binaries linearlly, and so if there are non-instructions in the `.text` section the disassembly will fail. 

Can you share the terminal output?

**Comment by RadonCoding** [comment] 2022-08-22 04:33
I removed the check for `assert_ne!(j_true, 0);` and the part that is "not working" is that the runtime doesn't do anything.

[output-with-check.txt](https://github.com/melotic/rekk/files/9391233/output-with-check.txt)

[output-without-check.txt](https://github.com/melotic/rekk/files/9391234/output-without-check.txt)

**Comment by RadonCoding** [comment] 2022-08-22 04:35
Also [here](https://cdn.discordapp.com/attachments/975669189958311937/1011131258534907984/crack-me.exe) is the file i'm testing with.

**Comment by RadonCoding** [comment] 2022-08-25 17:50
Any updates?

**Comment by melotic** [comment] 2022-10-09 19:32
This will be fixed in me rewrite of rekk, you can follow along here: https://github.com/melotic/nanostorm

nanostorm utilizes ghidra to provide the disassembly, so this issue will be fixed there. It already supports linux binaries, albeit with no encryption & compression.

**Closed as completed by melotic** 2022-10-09 19:32 UTC
Labels: wontfix
